import product from "../../assets/img/Product1.png";
// const dateString = '2022-01-06';
// const date = new Date(dateString);
// const month = date.toLocaleString('default', { month: 'long' });
// const day = date.getDate();

const notificationData = [
  {
    id: 1,
    name: "Surfing at leasure",
    price: 1800,
    time: "Nov 10-29",
    isCompleted : false,
    isRevieved : false,
    imageUrl: product,
    activity: "We have added a new activity for you.",
     //timeline: "Nov 5",
     timeline:new Date('2022-03-01'),
  },
  {
    id: 2,
    name: "Surfing at leasure",
    price: 1800,
    time: "Nov 10-29",
    imageUrl: product,
    isCompleted : true,
    isRevieved : false,
    activity: "Congratulations Charlie!",
     //timeline: "Nov 5",
     timeline:new Date('2022-02-01'),
  },
  {
    id: 3,
    name: "Surfing at leasure",
    price: 1800,
    time: "Nov 10-29",
    imageUrl: product,
    isCompleted : true,
    isRevieved : true,
    activity: "We have added a new activity for you.",
     //timeline: "Nov 5",
     timeline:new Date('2022-05-01'),
  },
  {
    id: 4,
    name: "Surfing at leasure",
    price: 1800,
    time: "Nov 10-29",
    imageUrl: product,
    isCompleted : false,
    isRevieved : false,
    activity: "We have added a new activity for you.",
     //timeline: "Nov 5",
     timeline:new Date('2022-06-01'),
  },
  {
    id: 5,
    name: "Surfing at leasure",
    price: 1800,
    time: "Nov 10-29",
    imageUrl: product,
    isCompleted : true,
    isRevieved : false,
    activity: "We have added a new activity for you.",
    //timeline: "Nov 5",
    timeline:new Date('2022-07-01'),
  },
  {
    id: 6,
    name: "Surfing at leasure",
    price: 1800,
    time: "Nov 10-29",
    imageUrl: product,
    isCompleted : true,
    isRevieved : true,
    activity: "We have added a new activity for you.",
     //timeline: "Nov 5",
     timeline:new Date('2022-08-01'),
  },
  {
    id: 7,
    name: "Surfing at leasure",
    price: 1800,
    time: "Nov 10-29",
    imageUrl: product,isCompleted : false,
    isRevieved : false,
    activity: "We have added a new activity for you.",
    //timeline: "Nov 5",
    timeline:new Date('2022-09-01'),
  },
  {
    id: 8,
    name: "Surfing at leasure",
    price: 1800,
    time: "Nov 10-29",
    imageUrl: product,
    isCompleted : true,
    isRevieved : false,
    activity: "We have added a new activity for you.",
     //timeline: "Nov 5",
     timeline:new Date('2022-10-01'),
  },
];

export default notificationData;
